name: quran_kareem
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+4

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
  quran: ^1.3.3
  audioplayers: ^6.1.2
  just_audio: ^0.9.46
  shared_preferences: ^2.5.2
  intl: ^0.20.2
  geolocator: ^13.0.2
  permission_handler: ^11.3.1
  adhan: ^2.0.0+1
  location: ^8.0.0
  flutter_spinkit: ^5.2.1
  flutter_qiblah: ^3.1.0+1
  path_provider: ^2.1.5
  dio: ^5.8.0+1
  connectivity_plus: ^6.1.3
  curved_navigation_bar: ^1.0.6
  http: ^1.3.0
  youtube_player_flutter: ^9.1.0
  share_plus: ^10.1.4
  scroll_to_index: ^3.0.1
  url_launcher: ^6.3.1
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/


